/**
 * Centralized policy defaults. NO worker may hardcode these values inline.
 * All thresholds, limits, and configuration live here.
 */

export const POLICY_DEFAULTS = {
  MAX_OVERLAYS: 5,
  MAX_CURES_PER_DIAGNOSIS: 25,
  MAX_CONTENT_ITEMS_PER_BATCH: 50,
  CONFIDENCE_THRESHOLD_AUTO: 0.85,
  CONFIDENCE_THRESHOLD_REVIEW: 0.60,
  CONFIDENCE_THRESHOLD_REJECT: 0.30,
  AII_WEIGHT_CONTENT: 0.25,
  AII_WEIGHT_SCHEMA: 0.20,
  AII_WEIGHT_EEAT: 0.20,
  AII_WEIGHT_CITATIONS: 0.15,
  AII_WEIGHT_FRESHNESS: 0.10,
  AII_WEIGHT_STRUCTURE: 0.10,
  PROBE_TIMEOUT_MS: 10000,
  PROBE_MAX_RETRIES: 3,
  SCORE_DECAY_DAYS: 30,
  SCORE_DECAY_RATE: 0.02,
  EXAMINER_CATEGORY_COUNT: 600,
  ORCHESTRATOR_STAGE_COUNT: 12,
  CONTENT_MIN_WORD_COUNT: 150,
  CONTENT_MAX_WORD_COUNT: 5000,
  PROMO_FREE30_DAYS: 30,
  PROMO_FREE90_DAYS: 90,
  AFFILIATE_COMMISSION_INDEPENDENT: 0.20,
  AFFILIATE_COMMISSION_AGENCY: 0.30,
  AFFILIATE_COMMISSION_AFFILIATE_AGENCY: 0.40,
} as const;

export type PolicyKey = keyof typeof POLICY_DEFAULTS;
export type PolicyValue = typeof POLICY_DEFAULTS[PolicyKey];
