/**
 * Centralized policy defaults. NO worker may hardcode these values inline.
 * All thresholds, limits, and configuration live here.
 *
 * To add a new threshold: add it here, then reference via
 * TenantPolicy.resolve('KEY_NAME') in the worker.
 */

export const POLICY_DEFAULTS = {
  // ── Pipeline / CWAR thresholds ──
  CONFIDENCE_THRESHOLD_AUTO: 0.85,
  CONFIDENCE_THRESHOLD_REVIEW: 0.60,
  CONFIDENCE_THRESHOLD_REJECT: 0.30,

  // ── Examiner severity thresholds ──
  EXAMINER_SEVERITY_CRITICAL: 0.30,
  EXAMINER_SEVERITY_HIGH: 0.50,
  EXAMINER_SEVERITY_THRESHOLD: 0.70,

  // ── Examiner dimension scoring denominators ──
  // These control how many items are needed to reach 1.0 for each dimension family
  EXAMINER_CONTENT_DEPTH_DENOM: 50,
  EXAMINER_CONTENT_BREADTH_DENOM: 30,
  EXAMINER_CONTENT_ACCURACY_DENOM: 20,
  EXAMINER_SCHEMA_COVERAGE_DENOM: 10,
  EXAMINER_SCHEMA_RICHNESS_DENOM: 15,
  EXAMINER_EEAT_EXPERIENCE_DENOM: 20,
  EXAMINER_EEAT_EXPERTISE_DENOM: 30,
  EXAMINER_EEAT_AUTHORITY_DENOM: 25,
  EXAMINER_EEAT_TRUST_DENOM: 15,
  EXAMINER_CITATION_FREQUENCY_DENOM: 30,
  EXAMINER_CITATION_DIVERSITY_DENOM: 20,

  // ── Examiner baseline scores (for dimensions without data-driven scoring) ──
  EXAMINER_BASELINE_FRESHNESS: 0.70,
  EXAMINER_BASELINE_SCHEMA_VALIDITY: 0.80,
  EXAMINER_BASELINE_CITATION_ACCURACY: 0.60,
  EXAMINER_BASELINE_STRUCTURE_HIERARCHY: 0.70,
  EXAMINER_BASELINE_STRUCTURE_HIERARCHY_LOW: 0.30,
  EXAMINER_BASELINE_STRUCTURE_NAV: 0.60,
  EXAMINER_BASELINE_STRUCTURE_NAV_LOW: 0.20,
  EXAMINER_BASELINE_ACCESSIBILITY: 0.50,
  EXAMINER_BASELINE_SPEED: 0.70,
  EXAMINER_BASELINE_MOBILE: 0.60,
  EXAMINER_BASELINE_SECURITY: 0.80,

  // ── Cure compiler impact baselines ──
  CURE_IMPACT_CRITICAL: 0.80,
  CURE_IMPACT_HIGH: 0.60,
  CURE_IMPACT_MEDIUM: 0.40,
  CURE_IMPACT_LOW: 0.20,
  CURE_IMPACT_EVIDENCE_BOOST: 0.02,
  CURE_IMPACT_MAX_BOOST: 0.20,

  // ── Cure compiler priority values ──
  CURE_PRIORITY_CRITICAL: 100,
  CURE_PRIORITY_HIGH: 75,
  CURE_PRIORITY_MEDIUM: 50,
  CURE_PRIORITY_LOW: 25,

  // ── Cure compiler confidence ──
  CURE_CONFIDENCE_BASE: 0.50,
  CURE_CONFIDENCE_PER_EVIDENCE: 0.05,
  CURE_CONFIDENCE_MAX: 0.95,

  // ── AII weights ──
  AII_WEIGHT_CONTENT: 0.25,
  AII_WEIGHT_SCHEMA: 0.20,
  AII_WEIGHT_EEAT: 0.20,
  AII_WEIGHT_CITATIONS: 0.15,
  AII_WEIGHT_FRESHNESS: 0.10,
  AII_WEIGHT_STRUCTURE: 0.10,

  // ── Limits ──
  MAX_OVERLAYS: 5,
  MAX_CURES_PER_DIAGNOSIS: 25,
  MAX_CONTENT_ITEMS_PER_BATCH: 50,

  // ── Probing ──
  PROBE_TIMEOUT_MS: 10000,
  PROBE_MAX_RETRIES: 3,

  // ── Score decay ──
  SCORE_DECAY_DAYS: 30,
  SCORE_DECAY_RATE: 0.02,

  // ── Platform constants ──
  EXAMINER_CATEGORY_COUNT: 600,
  ORCHESTRATOR_STAGE_COUNT: 12,

  // ── Content generation ──
  CONTENT_MIN_WORD_COUNT: 150,
  CONTENT_MAX_WORD_COUNT: 5000,

  // ── Promo ──
  PROMO_FREE30_DAYS: 30,
  PROMO_FREE90_DAYS: 90,

  // ── Affiliate commissions ──
  AFFILIATE_COMMISSION_INDEPENDENT: 0.20,
  AFFILIATE_COMMISSION_AGENCY: 0.30,
  AFFILIATE_COMMISSION_AFFILIATE_AGENCY: 0.40,
} as const;

export type PolicyKey = keyof typeof POLICY_DEFAULTS;
export type PolicyValue = typeof POLICY_DEFAULTS[PolicyKey];
