name = "411bz-schema-engine"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "0a99972e989785e2bf99eb4bef63dd21"
[vars]
WORKER_ID = "411bz-schema-engine"

[[d1_databases]]
binding = "DB"
database_name = "schema-engine-production"
database_id = "77a9b2b9-51e7-49fd-8593-6468721ad296"

[[services]]
binding = "ENGINE"
service = "411bz-authority-engine"

[[services]]
binding = "OBSERVATORY"
service = "411bz-observatory"
