name = "411bz-frontend"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "0a99972e989785e2bf99eb4bef63dd21"
[vars]
WORKER_ID = "411bz-frontend"
[[services]]
binding = "ENGINE"
service = "411bz-authority-engine"
[[services]]
binding = "ORCHESTRATOR"
service = "411bz-orchestrator"

[[services]]
binding = "OBSERVATORY"
service = "411bz-observatory"

[[services]]
binding = "BOSS_AI"
service = "411bz-boss-ai"
